# NumPy Introduction

## What is NumPy?

NumPy is a Python library used for numerical computing.
It provides support for arrays and mathematical operations
on large amounts of data.

## Why do we use NumPy?

- Fast numerical calculations
- Working with arrays
- Mathematical operations
- Statistical operations
- Useful for Data Analysis and Machine Learning

##  Installing NumPy

NumPy can be installed using the `pip` package manager.

The following command is used to install NumPy:

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


##  Importing NumPy

After installing NumPy, we need to import it into our Python program.

The commonly used alias for NumPy is `np`.

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.3.5


##  What is NumPy Array?

A NumPy array is a collection of elements stored in a structured way.
It is used to store and perform operations on numerical data efficiently.

NumPy arrays are created using the `np.array()` function.

### Example

Let's create a NumPy array containing five numbers.

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


### Example of a 2D NumPy Array

A 2D array contains data in rows and columns, similar to a table.

In [5]:
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr_2d)

[[10 20 30]
 [40 50 60]]


# NumPy Array vs Python List

Python List and NumPy Array are both used to store multiple values,
but they are different in terms of performance, data type, and operations.

## Difference Between Python List and NumPy Array

| Feature | Python List | NumPy Array |
|---|---|---|
| Library | Built-in Python | NumPy library |
| Speed | Comparatively slower | Faster for numerical operations |
| Data Type | Can store different data types | Generally stores same data type |
| Memory | Uses more memory | Uses less memory |
| Mathematical Operations | Limited | Easy and efficient |
| Numerical Data | Less suitable | Very suitable |
| Multidimensional Data | Possible but less efficient | Very efficient |

## Example

Python List:

In [7]:
my_list = [10, 20, 30, 40, 50]

print(my_list)
print(type(my_list))

[10, 20, 30, 40, 50]
<class 'list'>


In [8]:
import numpy as np

my_array = np.array([10, 20, 30, 40, 50])

print(my_array)
print(type(my_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [9]:
my_list = [10, 20, 30]

print(my_list * 2)

[10, 20, 30, 10, 20, 30]


In [10]:
my_array = np.array([10, 20, 30])

print(my_array * 2)

[20 40 60]


## Creating Arrays with Dimensions

Now we will create a NumPy `ndarray` object.  
The array object in NumPy is called `ndarray`.  
The `array()` function is used to create an `ndarray` object.

In [12]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


we can also pass a list, tuple or any array like object with array(). and it will be converted to ndarray

In [13]:
import numpy as np
y = np.array((1,2,3,4,5))
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimension in Arrays

a dimensions in arrays is one level of array depth(nested array).

# 0-D Arrays - Scalars

A 0-D array is an array that contains a single value.

Each value in an array is called a scalar.

## Creating a 0-D Array

Now we will create a 0-D array with the value 42.

In [14]:
import numpy as np

arr = np.array(42)

print(arr)
print(arr.ndim)

42
0


# 1-D Arrays

A 1-D array is an array that contains a sequence of values in a single dimension.

A 1-D array is also called a Vector.

It is created using the `np.array()` function.

## Example

Now we will create a 1-D array with the values [1, 2, 3, 4, 5].

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print("Number of dimensions:", arr.ndim)


[1 2 3 4 5]
Number of dimensions: 1


# 2-D Arrays

A 2-D array is an array that contains multiple 1-D arrays.

A 2-D array is also called a Matrix.

It contains data in rows and columns.

## Example

Now we will create a 2-D array with two rows and three columns.

In [16]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)
print("Number of dimensions:", arr.ndim)

[[1 2 3]
 [4 5 6]]
Number of dimensions: 2


# 3-D Arrays

A 3-D array is an array that contains multiple 2-D arrays.

It can be visualized as a collection of matrices or layers.

A 3-D array has three dimensions: depth, rows, and columns.

## Example

Now we will create a 3-D array with two 2-D arrays.

In [17]:
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr)
print("Number of dimensions:", arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions: 3


# Check how many dimensions the array have ndim attribute

In [19]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


# Create an array with 5 dimensions and verify that it has 5 dimensions

In [25]:
import numpy as np

sharad = np.array([1, 2, 3, 4, 5], ndmin=5)

print(sharad)
print("Number of dimensions:", sharad.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimensions: 5
