# Copy and View

#We will make a copy, change the copy, and display both arrays.

In [2]:
import numpy as np
ajeet = np.array([1,2,3,4,5])
ajeet1 = ajeet.copy()
print(ajeet)
print(ajeet1)

[1 2 3 4 5]
[1 2 3 4 5]


In [3]:
import numpy as np
ajeet = np.array([1,2,3,4,5])
ajeet1 = ajeet.copy()
ajeet1[0] = 12
print(ajeet)
print(ajeet1)

[1 2 3 4 5]
[12  2  3  4  5]


#Now we will create a view, change the view, and display both arrays.

In [5]:
import numpy as np
ajeet = np.array([1,2,3,4,5])
ajeet1 = ajeet.view()
print(ajeet)
print(ajeet1)

[1 2 3 4 5]
[1 2 3 4 5]


In [6]:
import numpy as np
ajeet = np.array([1,2,3,4,5])
ajeet1 = ajeet.view()
ajeet1[0] = 12
print(ajeet)
print(ajeet1)

[12  2  3  4  5]
[12  2  3  4  5]


# Difference Between Copy and View in NumPy

| Copy                                       | View                                     |
| ------------------------------------------ | ---------------------------------------- |
| Creates a **new array**                    | Creates a **view of the original array** |
| Has **separate memory**                    | Shares the **same underlying data**      |
| Changes in copy **do not affect** original | Changes in view **can affect** original  |
| Uses more memory                           | Uses less memory                         |
| Created using `copy()`                     | Created using `view()`                   |
