# NumPy Array Reshaping

## Reshaping means changing the shape of an array without changing its elements.

#Reshaping from 1-D to 2-D

In [2]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ajeet1 = ajeet.reshape(4, 3)
print(ajeet1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#Reshaping from 1-D to 3-D

In [4]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ajeet1 = ajeet.reshape(2, 3, 2)
print(ajeet1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#Return copy or view

In [5]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8])
print(ajeet.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


#Unknown dimension - you are only allowed to have one unknown dimension. Pass -1.

In [6]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8])
ajeet1 = ajeet.reshape(2,2,-1)
print(ajeet1)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#Flattening the array by converting a multidimensional array into 1-D

In [10]:
import numpy as np
ajeet = np.array([[1,2,3],[4,5,6]])
ajeet1 = ajeet.reshape(-1)
print(ajeet1)

[1 2 3 4 5 6]


There are a lot of functions for changing the shape of an array in NumPy, such as flatten, ravel, rot90, flip, fliplr, and flipud.