# Numpy joining Array

## Here for this we will pass concatenate()

In [2]:
import numpy as np
x = np.array([1,2,3])
x1 = np.array([4,5,6])
x2 = np.concatenate((x,x1))
print(x2)

[1 2 3 4 5 6]


#joining of 2-D array along with rows(axis = 1)

In [3]:
import numpy as np
x = np.array([[1,2],[3,4]])
x1 = np.array([[5,6],[7,8]])
x2 = np.concatenate((x,x1), axis = 1)
print(x2)

[[1 2 5 6]
 [3 4 7 8]]


#joining array usiing the stack function:

In [7]:
import numpy as np
x = np.array([1,2,3])
x1 = np.array([4,5,6])
x2 = np.stack((x,x1),axis=1)
print(x2)

[[1 4]
 [2 5]
 [3 6]]


#stacking along with row: hstack()

In [9]:
import numpy as np
x = np.array([1,2,3])
x1 = np.array([4,5,6])
x2 = np.hstack((x,x1))
print(x2)

[1 2 3 4 5 6]


#stacking along with column

In [10]:
import numpy as np
x = np.array([1,2,3])
x1 = np.array([4,5,6])
x2 = np.vstack((x,x1))
print(x2)

[[1 2 3]
 [4 5 6]]


#stacking along with height(depth)

In [11]:
import numpy as np
x = np.array([1,2,3])
x1 = np.array([4,5,6])
x2 = np.dstack((x,x1))
print(x2)

[[[1 4]
  [2 5]
  [3 6]]]
