# Searching Array

## you can Search an array for a certain value and return the indexes that get the match. 

#by using where()

In [2]:
import numpy as np
x = np.array([1,2,3,4,5,4,4])
x1 = np.where(x == 4)
print(x1)

(array([3, 5, 6]),)


#now we will find the indexes where the value are even:

In [3]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
x1 = np.where(x%2 == 0)
print(x1)

(array([1, 3, 5, 7]),)


#now we will find the indexes where the values are add: 

In [4]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
x1 = np.where(x%2 == 1)
print(x1)

(array([0, 2, 4, 6]),)


# Searchsorted()

perform binary search in array.

#we will now find the index where the value 7 should be insterted.

In [7]:
import numpy as np
x = np.array([6,7,8,9])
x1 = np.searchsorted(x,7)
print(x1)

1


#now we will search form right Side

In [8]:
import numpy as np
x = np.array([6,7,8,9])
x1 = np.searchsorted(x,7, side='right')
print(x1)

2


#how to search multiple values.

In [9]:
import numpy as np
x = np.array([1,3,5,7])
x1 = np.searchsorted(x,[2,4,6])
print(x1)

[1 2 3]


# Sort()

the numpy ndarray object has a function which is called Sort(). and this will sort a Specified array.

In [5]:
import numpy as np
x = np.array([3,2,0,1])
print(np.sort(x))

[0 1 2 3]


#sort the array alphabetically

In [6]:
import numpy as np
x = np.array(["banana", "cherry", "apple"])
print(np.sort(x))

['apple' 'banana' 'cherry']


#sort the boolean array

In [1]:
import numpy as np
x = np.array([True, False, True])
print(np.sort(x))

[False  True  True]


#sorting the 2-D array

In [8]:
import numpy as np
x = np.array([[3,2,4],[5,0,1]])
print(np.sort(x))

[[2 3 4]
 [0 1 5]]
