# Random Number

## Random meaning - something that cannot be predicted logically.

#Now we will generate a random number from 0 to 100.

In [2]:
from numpy import random
x = random.randint(100)
print(x)

64


#you can also generate floats using rand()

In [4]:
from numpy import random
x = random.rand()
print(x)

0.6423329625421297


#you can also generate random array.

#we will generate a 1-D array containing 5 random int from 0 to 100.

In [9]:
from numpy import random
x = random.randint(100, size=(5))
print(x)

[37 86 78 44 88]


#we will generate a 2-D array with 3 rows, each row containing 5 random int from 0 to 100.

In [10]:
from numpy import random
x = random.randint(100, size=(3,5))
print(x)

[[49  0 68 34 60]
 [20 22 59  8 51]
 [51 30 98 49 33]]


#we will generate a 1-D array containing 5 random float.

In [11]:
from numpy import random
x = random.rand(5)
print(x)

[0.14443622 0.06482301 0.61581864 0.30129431 0.40694885]


#we will generate a 2-D array with 3 rows, each containing 5 random float.

In [14]:
from numpy import random
x = random.rand(3,5)
print(x)

[[0.28261845 0.27767559 0.38310823 0.49848652 0.91309171]
 [0.48560034 0.79401084 0.84505588 0.50419219 0.17624429]
 [0.47167451 0.70687351 0.02366748 0.13480674 0.25959087]]


#you can also generate random numbers from an array

#choice()

In [17]:
from numpy import random
x = random.choice([3,5,7,9,1,4,6])
print(x)

3


#you will also generate random numbers froms an 2-D array

#choice()

In [18]:
from numpy import random
x = random.choice([3,5,7,9,1,4,6],size=(3,5))
print(x)

[[5 1 1 5 5]
 [9 4 3 4 9]
 [6 4 6 1 1]]
