# Random Data Distribution

## #Data distribution describes possible values and how often they occur.

## #Such lists are important when working with statistics and data science.

## #Random distribution: Probability function

## #now we will generate 1-D with 100 values where each value has to be 3,5,7,9

## #the probability for the value 3 is set to be 0.1

## #the probability for the value 5 is set to be 0.3

## #the probability for the value 7 is set to be 0.6

## #the probability for the value 9 is set to be 0

## #The sum of all probabilities should be 1.

In [11]:
import numpy as np

x = np.random.choice(
    [3, 5, 7, 9],
    p=[0.1, 0.3, 0.6, 0.0],
    size=100
)

print(x)

[7 7 5 7 3 3 7 7 7 3 7 7 3 5 7 7 5 7 7 7 3 5 5 7 7 3 5 5 5 7 5 7 3 7 7 7 7
 7 5 5 5 7 5 5 7 3 7 5 7 7 5 7 7 7 7 7 7 5 7 5 3 7 7 7 7 7 7 3 7 7 5 7 5 7
 7 7 7 3 5 5 7 7 5 3 7 7 7 5 7 5 7 7 5 7 7 5 3 7 7 7]


#now we will return 2-D with 3 rows each containing 5 values

In [12]:
import numpy as np

x = np.random.choice(
    [3, 5, 7, 9],
    p=[0.1, 0.3, 0.6, 0.0],
    size=(3,5)
)

print(x)

[[7 5 7 7 7]
 [7 5 7 5 3]
 [3 7 7 7 7]]


# Random Permutation

## Permutation - Permutation refers to an arrangement of element like [3,2,1] is permutation of [1,2,3], and vice versa.

#the numpy random module provides 2 methods: shuffle() and permutation().  

#The shuffle() method changes the original array.

#now we will randomly shuffle elements for the below array

In [16]:
from numpy import random
import numpy as np
x = np.array([1,2,3,4,5])
random.shuffle(x)
print(x)

[5 3 2 1 4]


#now we will generate a permutation of elements for the below array.

In [18]:
from numpy import random
import numpy as np
x = np.array([1,2,3,4,5])
random.permutation(x)
print(x)

[1 2 3 4 5]


#The permutation() method returns a shuffled copy and leaves the original array unchanged.

In [19]:
from numpy import random
import numpy as np
x = np.array([1,2,3,4,5])
print(random.permutation(x))

[2 5 3 1 4]
