# Slicing array - slicing in python means taking elements from one given index to another index.

# [start : end] , [start:end:step]

#Now we will slice elements from index 1 to 5.

In [1]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9])
print(ajeet[1:5])

[2 3 4 5]


In [2]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9])
print(ajeet[4:])

[5 6 7 8 9]


In [3]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9])
print(ajeet[:4])

[1 2 3 4]


Negative Slicing

In [12]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9])
print(ajeet[-6:-1])

[4 5 6 7 8]


In [14]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7])
print(ajeet[-3:-1])

[5 6]


Step: The step value determines the step size of the slicing.

return every other value from index 1 to 5.

In [15]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7])
print(ajeet[1:5:2])

[2 4]


now return every other number from the entire array.

In [16]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9])
print(ajeet[::2])

[1 3 5 7 9]


In [17]:
import numpy as np
ajeet = np.array([1,2,3,4,5,6,7,8,9])
print(ajeet[::3])

[1 4 7]


slicing 2-D array: print 7,8,9

In [19]:
import numpy as np
ajeet = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ajeet[1,1:4])

[7 8 9]


another example

In [20]:
import numpy as np
ajeet = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ajeet[0:2,2])

[3 8]


Another example: 2-D array slicing from index 1 to 4.

In [22]:
import numpy as np
ajeet = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ajeet[0:2,1:4])

[[2 3 4]
 [7 8 9]]


slicing 3-D array

In [23]:
import numpy as np

ajeet = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(ajeet[0])

[[1 2 3]
 [4 5 6]]


In [24]:
ajeet = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(ajeet[0,0])

[1 2 3]


In [25]:
ajeet = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(ajeet[0, :, 0:2])

[[1 2]
 [4 5]]
